config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/signup' => 'welcome#signup'
  get '/contractor/signup' => 'contractors#new'
  post '/contractor/signup' => 'contractors#create'
  get '/client/signup' => 'clients#new'
  post '/client/create' => 'clients#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  match "/auth/google_oauth2/callback" => 'sessions#googlelogin', via: [:get, :post]


  resources :reviews do
    collection do
      get 'high_to_low' => 'reviews#index', status: 'high_to_low'
      get 'low_to_high' => 'reviews#index', status: 'low_to_high'
    end
  end
  resources :appointments do
    resources :reviews, only: [:new, :create, :index]
  end
  resources :contractors do
    resources :appointments, only: [:new, :create, :index]
    resources :reviews, only: [:index]
  end
  resources :clients do
    resources :appointments, only: [:new, :create, :index] do
      resources :reviews, only: [:new, :create, :index]
    end
    resources :reviews, only: [:new, :create, :index]
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def home
        
    end

    def signup

    end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<h1>Welcome to the Contractor Review App!</h1>

<p>Clients and Contractors can sign up for our app, schedule appointments with eachother,
and review the work done after the job has been completed.<br>
<br>
Clients can also browse reviews written by other clients to see which contractor would fit
best for their job.<br>
<br>
Please <%= link_to "Sign Up", signup_path %> for the app so you can get started schuduling
your next home improvement!<br>

app/views/welcome/signup.html.erb
<h3>Sign up as <%= link_to "Client", client_signup_path %></h3>
<h3>Sign up as <%= link_to "Contractor", contractor_signup_path %></h3>