config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/signup' => 'welcome#signup'
  get '/contractor/signup' => 'contractors#new'
  post '/contractor/signup' => 'contractors#create'
  get '/client/signup' => 'clients#new'
  post '/client/create' => 'clients#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  match "/auth/google_oauth2/callback" => 'sessions#googlelogin', via: [:get, :post]


  resources :reviews do
    collection do
      get 'high_to_low' => 'reviews#index', status: 'high_to_low'
      get 'low_to_high' => 'reviews#index', status: 'low_to_high'
    end
  end
  resources :appointments do
    resources :reviews, only: [:new, :create, :index]
  end
  resources :contractors do
    resources :appointments, only: [:new, :create, :index]
    resources :reviews, only: [:index]
  end
  resources :clients do
    resources :appointments, only: [:new, :create, :index] do
      resources :reviews, only: [:new, :create, :index]
    end
    resources :reviews, only: [:new, :create, :index]
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :client, inverse_of: :appointments
    belongs_to :contractor, inverse_of: :appointments
    has_one :review

    validates :appointment_time, uniqueness: { scope: :contractor_id }
    validates :appointment_time, presence: true
    validates :job_name, presence: true
    validates :job_description, presence: true

end

app/controllers/appointments_controller.rb
require 'pry'
class AppointmentsController < ApplicationController
    before_action :require_login

    def index
        if params[:client_id] && @client = Client.find_by_id(params[:client_id])
            @appointments = @client.appointments
        elsif params[:contractor_id] && @contractor = Contractor.find_by_id(params[:contractor_id])
            @appointments = @contractor.appointments
        else
            @error = flash[:message] = "Client and/or Contractor has no Appointments" if params[:client_id] || params[:contractor_id]
            @appointments = Appointment.all
        end
    end

    def new
        @appointment = Appointment.new
    end

    def create
        @appointment = current_user.meta.appointments.build(appointment_params)
        if @appointment.save
            redirect_to @appointment
        else
            render :new
        end
    end

    def show
        @appointment = Appointment.find_by_id(params[:id])
    end

    private

    def appointment_params
        params.require(:appointment).permit(:job_name, :job_description, :appointment_time, :client_id, :contractor_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/index.html.erb
<h1>Appointments </h1>
<% @appointments.each do |appointment| %>
    <% if client_user %>
    <ul>
        <li>
        <h3>Project Name: <%= appointment.job_name %></h3></li>
        <strong>Contractor Business Name: </strong><%= appointment.contractor.business_name %><br>
        <strong>Contractor License Number: </strong><%= appointment.contractor.license_number %><br>
        <strong>Project Description: </strong><%= appointment.job_description %><br>
        <strong>Appointment Time: </strong><%= appointment.appointment_time %><br>
        <%= link_to "Write A Review", new_client_appointment_review_path(@client.id, appointment.id) %>
        <br>
        <br>
        </li>
    </ul>
    <% elsif contractor_user %>
    <ul>
    <li>
    <h3>Project Name: <%= appointment.job_name %></h3></li>
    <strong>Project Description: </strong><%= appointment.job_description %><br>
    <strong>Appointment Time: </strong><%= appointment.appointment_time %><br>
    <br>
    <br>
    </li
    <% end %>
<% end %>

app/views/appointments/new.html.erb
<h1> Request an Appontment from a Contractor</h1>

<% if @appointment.errors.any? %>
  <% @appointment.errors.full_messages.each do |message|%>
  <h3><%= message %> </h3>
  <%end%>
<%end%>

<%= form_for (@appointment) do |f| %>

    <strong><%= f.label :contractor_id, "Contractor Name" %></strong>
    <%= f.collection_select :contractor_id, Contractor.all, :id, :business_name %><br>
        <br>
    <strong><%= f.label :job_name, "Job Name" %></strong>
    <%= f.text_field :job_name %><br>
        <br>
    <strong><%= f.label :job_description, "Job Description" %></strong>
    <%= f.text_field :job_description %><br>
        <br>
    <strong><%= f.label :appointment_time, "Appointment Time" %></strong>
    <%= f.datetime_field(:appointment_time, placeholder: "yyyy-mm-dd", min: Date.today) %><br>
        <br>
    <%= f.submit %>

<% end %>

app/views/appointments/show.html.erb
<h1>Appointment Requested </h1>
<strong>Contractor: </strong> <%= @appointment.contractor.business_name %><br>
<strong>Contractor License: </strong> <%= @appointment.contractor.license_number %><br>
<br>
<strong>Job Name: </strong><%= @appointment.job_name %><br>
<strong>Job Description: </strong><%= @appointment.job_description %></br>
<strong>Appointment Time: </strong><%= @appointment.appointment_time %></br>