config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/signup' => 'welcome#signup'
  get '/contractor/signup' => 'contractors#new'
  post '/contractor/signup' => 'contractors#create'
  get '/client/signup' => 'clients#new'
  post '/client/create' => 'clients#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  match "/auth/google_oauth2/callback" => 'sessions#googlelogin', via: [:get, :post]


  resources :reviews do
    collection do
      get 'high_to_low' => 'reviews#index', status: 'high_to_low'
      get 'low_to_high' => 'reviews#index', status: 'low_to_high'
    end
  end
  resources :appointments do
    resources :reviews, only: [:new, :create, :index]
  end
  resources :contractors do
    resources :appointments, only: [:new, :create, :index]
    resources :reviews, only: [:index]
  end
  resources :clients do
    resources :appointments, only: [:new, :create, :index] do
      resources :reviews, only: [:new, :create, :index]
    end
    resources :reviews, only: [:new, :create, :index]
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :require_login


    def index
        if params[:client_id] && @client = Client.find_by_id(params[:client_id])
            @reviews = @client.reviews
        elsif params[:contractor_id] && @contractor = Contractor.find_by_id(params[:contractor_id])
            @reviews = @contractor.reviews
        else
            @error = flash[:message] = "Client and/or Contractor has no Reviews" if params[:client_id] || params[:contractor_id]
            @reviews = Review.all
                if params["status"]["high_to_low"]
                    @reviews = Review.high_to_low
                elsif params["status"]["low_to_high"]
                    @reviews = Review.low_to_high
                end
        end
    end

    def new
        @appointment = Appointment.find_by_id(params[:appointment_id])
        if params[:appointment_id] && Appointment.find_by_id(params[:appointment_id])
            if @appointment.review
                flash[:message] = "You already reviewed this appointment"
                redirect_to @appointment.review
            else
                @review = @appointment.build_review
            end
        else
            @error = flash[:message] = "That appointment doesn't exist" if params[:appointment_id]
            @review = Review.new
        end
    end

    def create
        @appointment = Appointment.find_by_id(params[:review][:appointment_id])
        if @appointment.review != nil
            flash[:message] = "You already reviewed this appointment"
            redirect_to @appointment.review
        else
            @review = Review.new(review_params)
            if @review.save
                redirect_to @review
            else
                render :new 
            end
        end
    end

    def show
        @review = Review.find_by_id(params[:id])
    end

    private

    def review_params
        params.require(:review).permit(:rating, :content, :appointment_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<%  @reviews.each do |review|  %>
    <ul>
        <li>
        <h3>Project Name: <%= review.appointment.job_name %></h3>
        <strong>Contractor Rating:</strong> <%= review.rating %>/10<br>
        <strong>Review:</strong> <%= review.content %><br>
        </li>
    </ul>
<% end %>

<%= link_to 'Ratings from High to Low', high_to_low_reviews_path %> || <%= link_to 'Ratings from Low to High', low_to_high_reviews_path %>

app/views/reviews/new.html.erb
<% if @review.appointment %>
<h1>Write a Review for <%= @review.appointment.job_name %></h1>
<% else %>
<h1>Write a Review!</h1>
<% end %>

<% if @review.errors.any? %>
  <% @review.errors.full_messages.each do |message|%>
  <h3><%= message %> </h3>
  <%end%>
<%end%>

<%= form_for([@review.appointment, @review]) do |f| %>

    <% if !@review.appointment %>
      <strong><%= f.label :appointment_id, "Project Name" %><strong>
      <%= f.collection_select :appointment_id, Appointment.where(:client_id => client_user), :id, :job_name %><br>
    <% else %>
      <%= f.hidden_field :appointment_id %>
    <% end %>
    <br>
    <strong><%= f.label :rating, "Rate the Job 1-10" %></strong>
    <%= f.number_field :rating %><br>
    <br>
    <strong><%= f.label :content, "Why did you give this Rating" %></strong>
    <%= f.text_field :content %><br>
    <br>
    <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<h1>My Review!</h1>
  <strong> Contractor Rating:</strong>  <%= @review.rating %><br>
  <strong> Review: </strong> <%= @review.content %>