config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/signup' => 'welcome#signup'
  get '/contractor/signup' => 'contractors#new'
  post '/contractor/signup' => 'contractors#create'
  get '/client/signup' => 'clients#new'
  post '/client/create' => 'clients#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  match "/auth/google_oauth2/callback" => 'sessions#googlelogin', via: [:get, :post]


  resources :reviews do
    collection do
      get 'high_to_low' => 'reviews#index', status: 'high_to_low'
      get 'low_to_high' => 'reviews#index', status: 'low_to_high'
    end
  end
  resources :appointments do
    resources :reviews, only: [:new, :create, :index]
  end
  resources :contractors do
    resources :appointments, only: [:new, :create, :index]
    resources :reviews, only: [:index]
  end
  resources :clients do
    resources :appointments, only: [:new, :create, :index] do
      resources :reviews, only: [:new, :create, :index]
    end
    resources :reviews, only: [:new, :create, :index]
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContractorReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <br>
    <% if client_user && logged_in? %>
      <%= link_to "Home", client_path(client_user) %> |
      <%= link_to "My Appointments", client_appointments_path(client_user) %> |
      <%= link_to "My Reviews", client_reviews_path(client_user) %> |
      <%= link_to "Request an Appointment", new_appointment_path %> | 
      <%= link_to "Write a Review", new_review_path %> | 
    <% elsif contractor_user %>
      <%= link_to "Home", contractor_path(contractor_user) %> | 
      <%= link_to "My Appointments", contractor_appointments_path(contractor_user)%> | 
      <%= link_to "My Reviews", contractor_reviews_path(contractor_user) %> | 
    <% end %>
<% if logged_in? %>
  <%= link_to "View Contractors", contractors_path %> | 
  <br>
  <br>
  <%= button_to("Logout", logout_path, method: :delete) %>
<% else %>
  <%= link_to "Sign Up", signup_path %> | 
  <%= link_to "Login", login_path %><br>
<% end %>

<br>
<br>
  </head>

  <body>
    <% if flash[:message] %>
      <%= flash[:message] %>
    <% end %>
    <%= @error %>
    <%= yield %>
  </body>
</html>